config/routes.rb
Rails.application.routes.draw do
  root "posts#index"
  devise_for :users
  resources :users
  resources :posts
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new # Guest user (not logged in)

    if user.has_role?(:admin)
      can :manage, User # Admins can manage User resources
    else
      cannot :read, User # Non-admins can only read User resources
      # Define other abilities as needed for your application
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
end

app/models/role.rb
class Role < ApplicationRecord
  has_and_belongs_to_many :users, :join_table => :users_roles
  
  belongs_to :resource,
             :polymorphic => true,
             :optional => true
  

  validates :resource_type,
            :inclusion => { :in => Rolify.resource_types },
            :allow_nil => true

  scopify
end

app/models/user.rb
class User < ApplicationRecord
  rolify
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :posts, dependent: :destroy

  after_create :assign_default_role

  def assign_default_role
    self.add_role(:newuser) if self.roles.blank?
  end

  validate :must_have_a_role, on: :update

  private
  def must_have_a_role
    unless roles.any?
      errors.add(:roles, "Must have at least one role!")
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!


  def after_sign_in_path_for(resource)
    # Customize the sign-in redirect path
    root_path
  end

  def after_sign_out_path_for(resource)
    # Customize the sign-out redirect path
    new_user_session_path
  end

  rescue_from CanCan::AccessDenied do |exception|
    redirect_to root_path, notice: "Unauthorized access. You are not authorized to perform this action."
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_post, only: %i[ show edit update destroy ]

  # GET /posts or /posts.json
  def index
    @posts = current_user.posts
  end

  # GET /posts/1 or /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts or /posts.json
  def create
    @post = current_user.posts.build(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to post_url(@post), notice: "Post was successfully created." }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to post_url(@post), notice: "Post was successfully updated." }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    @post.destroy

    respond_to do |format|
      format.html { redirect_to posts_url, notice: "Post was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:title)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  load_and_authorize_resource
  before_action :authenticate_user!
  # before_action :check_admin_role, only: [:index, :edit, :update]
  def index
    @users = User.order(created_at: :asc)
  end

  def edit
    @user = User.find(params[:id])
    authorize! :edit, @user
  end

  def update
    respond_to do |format|
      @user = User.find(params[:id])
      if @user.update(user_params)
        format.html { redirect_to users_url, notice: "User role was successfully updated." }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  private

  def user_params
    params.require(:user).permit({ role_ids: [] })
  end

  # def check_admin_role
  #   unless current_user.has_role?(:admin)
  #     redirect_to root_path, alert: "Unauthorized access. Only administrators can perform this action."
  #   end
  # end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light shadow">
  <a class="navbar-brand" href="/">Rolify</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <a class="nav-link" href="/">Home</a>
      </li>
      <li class="nav-item">
        <% if user_signed_in? && current_user.roles.pluck(:name).include?('admin') %>
          <a class="nav-link" href="/users">Manage Users</a>
        <% else %>
<!--          <a class="nav-link" href="/">Unauthorized</a>-->
        <% end %>
      </li>
    </ul>
    <ul class="navbar-nav custom-mx">
      <% if user_signed_in? %>
        <li class="nav-item">
          <%= form_tag(destroy_user_session_path, method: :delete) do %>
            <%= submit_tag("Sign Out", class: "btn btn-sm btn-danger") %>
          <% end %>
        </li>
      <% else %>
        <li class="nav-item">
          <a class="nav-link" href="/users/sign_in">Login</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="/users/sign_up">Signup</a>
        </li>
      <% end %>
    </ul>
  </div>
</nav>

<style>
    .navbar-nav.custom-mx {
        margin-left: auto !important; /* Adjust the margin as needed */
    }
</style>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RolifyExample</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>

  <%= render "layouts/navbar" %>
  <% if user_signed_in? %>
    <p class="text-center">Logged in as: <%= current_user.email %></p>
    <% if current_user.has_any_role? %>
      <p class="text-center">Member Type: <%= current_user.roles.pluck(:name).map(&:titleize).join(', ') %></p>
    <% end %>
  <% end %>
  <div class="container">
    <%= yield %>
  </div>

  </body>
</html>

app/views/posts/_form.html.erb
<%= form_with(model: post) do |form| %>
  <% if post.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% post.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/posts/_post.html.erb
<div id="<%= dom_id post %>">
  <p>
    <strong>Title:</strong>
    <%= post.title %>
  </p>

</div>

app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render "form", post: @post %>

<br>

<div>
  <%= link_to "Show this post", @post %> |
  <%= link_to "Back to posts", posts_path %>
</div>

app/views/posts/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Posts</h1>

<div id="posts">
  <% @posts.each do |post| %>
    <%= render post %>
    <p>
      <%= link_to "Show this post", post %>
    </p>
  <% end %>
</div>

<%= link_to "New post", new_post_path %>

app/views/posts/new.html.erb
<h1>New post</h1>

<%= render "form", post: @post %>

<br>

<div>
  <%= link_to "Back to posts", posts_path %>
</div>

app/views/posts/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @post %>

<div>
  <%= link_to "Edit this post", edit_post_path(@post) %> |
  <%= link_to "Back to posts", posts_path %>

  <%= button_to "Destroy this post", @post, method: :delete %>
</div>

app/views/users/edit.html.erb
<table class="table table-bordered table-hover table-bordered">
  <thead class="bg-dark text-white">
  <tr>
    <th>Role</th>
    <th>Checkbox</th>
  </tr>
  </thead>
  <tbody>
  <%= form_with(model: @user, html: { class: "form-horizontal" }) do |form| %>
    <% Role.all.each do |role| %>
      <tr>
        <td><%= role.name %></td>
        <td>
          <%= form.check_box :role_ids, { multiple: true }, role.id, nil %>
        </td>
      </tr>
    <% end %>
    </tbody>
    </table>

    <div class="form-group">
      <div class="col-sm-offset-2 col-sm-10">
        <%= form.button :submit, class: "btn btn-primary" %>
        <%= link_to "Back", users_path, class: "btn btn-secondary" %>
      </div>
    </div>

    <div class="form-group">
      <div class="col-sm-offset-2 col-sm-10">
        <% if @user.errors[:role_ids].any? %>
          <div class="text-danger">
            <%= @user.errors[:role_ids].first %>
          </div>
        <% end %>
      </div>
    </div>
  <% end %>

app/views/users/index.html.erb
  <table class="table table-hover table-stripped table-bordered">
    <thead class="bg-dark text-white">
      <tr>
        <th>#</th>
        <th>Email</th>
        <th>Role</th>
        <th>Action</th>
      </tr>
    </thead>
    <tbody>
    <% @users.each_with_index do |user,i| %>
      <tr>
        <td><%= i+1 %></td>
        <td><strong><%= user.email %></strong></td>
        <td><%= user.roles.pluck(:name) %></td>
        <td><%= link_to "Edit Roles", edit_user_path(user) %></td>
      </tr>
    <% end %>
    </tbody>
  </table>